var _config = {
	baseUrl : 'https://qwikbusinesstools.com/'
}
var apps={
	ms:[
		{
			"name":"Word",
			"url":"https://www.microsoft.com/microsoft-365/word"
		},
		{
			"name":"Excel",
			"url":"https://www.microsoft.com/microsoft-365/excel"
		},
		{
			"name":"PowerPoint",
			"url":"https://www.microsoft.com/microsoft-365/powerpoint"
		},
		{
			"name":"Publisher",
			"url":"https://www.microsoft.com/microsoft-365/publisher"
		},
        {
			"name":"Lync",
			"url":"https://www.microsoft.com/microsoft-365/previous-versions/microsoft-lync-2013"
		},
        {
 			"name":"Outlook",
			"url":"https://www.microsoft.com/microsoft-365/outlook"
		},
        {
 			"name":"SharePoint",
			"url":"https://www.microsoft.com/microsoft-365/sharepoint"
		},
        {
 			"name":"OneNote",
			"url":"https://www.microsoft.com/microsoft-365/onenote"
		},
        {
 			"name":"Visio",
			"url":"https://www.microsoft.com/microsoft-365/visio"
		},        
		{
 			"name":"Access",
			"url":"https://www.microsoft.com/microsoft-365/Access"
		},
        {
 			"name":"Sway",
			"url":"https://sway.office.com/"
		},
		{
 			"name":"Teams",
			"url":"https://www.microsoft.com/microsoft-teams"
		},
		{
 			"name":"Skype",
			"url":"https://skype.com"
		}
		
		
	],
	google:[
		{
			"name":"Gmail",
			"url":"https://gmail.com"
		},
		{
			"name":"Drive",
			"url":"https://drive.google.com"
		},
		{
			"name":"Hangouts",
			"url":"https://Hangouts.google.com"
		},
		{
			"name":"Calendar",
			"url":"https://calendar.google.com"
		},
		{
			"name":"Cloud Print",
			"url":"https://www.google.com/cloudprint/learn/print.html"
		},
		{
			"name":"Docs",
			"url":"https://docs.google.com"
		},
		{
			"name":"Sheets",
			"url":"https://sheets.google.com"
		},
		{
			"name":"Forms",
			"url":"https://forms.google.com"
		},
		{
			"name":"Slides",
			"url":"https://slides.google.com"
		},
		{
			"name":"Alerts",
			"url":"https://www.google.com/alerts"
		},
		{
			"name":"Books",
			"url":"https://books.google.com"
		},
		{
			"name":"Maps",
			"url":"https://maps.google.com"
		},
		{
			"name":"Analytics",
			"url":"https://analytics.google.com"
		}
		
	],
	apache:[
		{
			"name":"OpenOffice",
			"url":"https://www.openoffice.org/"
		},
		{
			"name":"Writer",
			"url":"https://www.openoffice.org/product/writer.html"
		},
		{
			"name":"Calc",
			"url":"https://www.openoffice.org/product/calc.html"
		},
		{
			"name":"Impress",
			"url":"https://www.openoffice.org/product/impress.html"
		},
		{
			"name":"Draw  ",
			"url":"https://www.openoffice.org/product/draw.html"
		},
		{
			"name":"Base  ",
			"url":"https://www.openoffice.org/product/base.html"
		},
		{
			"name":"Math  ",
			"url":"https://www.openoffice.org/product/math.html"
		}		
	]
};
